<?php
$post = $block->getPost();
$commentt = $block->getComment();
?>
<div class="post-header">
    <h1 class="blog-post-item-title"><?php echo $post->getTitle(); ?></h1>

    <img src="<?php echo $block->getImageUrl($post); ?>"
         height="600"
         width="800"/>
</div>
<div class="blog-post-item-meta">
    <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreatedAt(); ?>
    <strong><?php echo __('Update at:') ?></strong> <?php echo $post->getUpdateAt(); ?>
</div>
<div class="blog-post-item-content">
    <?php echo $post->getContent(); ?>
</div>

<div class="blog-post-item-content">
    <h2>Comments</h2>
    <?php foreach ($commentt as $comment):?>
    <div>Name: <?= $comment->getFirstName(); ?> <?= $comment->getLastName(); ?></div>
    <div><?= $comment->getComment(); ?></div>
    <div>commented at: <?= $comment->getCreateData(); ?></div>
    <div>comment status: <?= $block->getCommentStatus($comment->getAnswer()) ; ?></div>
        <br>
    <?php endforeach;?>
</div>
