<?php
$post = $block->getPost();
$comments = $block->getComment();
?>
<div class="post-header">
    <h1 class="blog-post-item-title"><?php echo $post->getTitle(); ?></h1>

    <img src="<?php echo $block->getImageUrl($post); ?>"
         height="<?= $block->getImageHeight(); ?>"
         width="<?= $block->getImageWidth(); ?>"/>
</div>
<div class="blog-post-item-meta">
    <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreatedAt(); ?>
    <strong><?php echo __('Update at:') ?></strong> <?php echo $post->getUpdateAt(); ?>
</div>
<div class="blog-post-item-content">
    <?php echo $post->getContent(); ?>
</div>

<div class="blog-post-item-content">
    <h2><?php echo __('Comments') ?></h2>
    <?php foreach ($comments as $comment):?>
    <div><?php echo __('Name: ') ?><?= $comment->getFirstName(); ?><?= $comment->getLastName(); ?></div>
    <div><?= $comment->getComment(); ?></div>
    <div><?php echo __('commented at: ') ?><?= $comment->getCreateData(); ?></div>
    <div><?php echo __('comment status: ') ?><?= $block->getCommentStatus($comment->getAnswer()) ; ?></div>
        <br>
    <?php endforeach;?>
</div>
<?php if ($block->getPagerHtml()) : ?>
    <div class="blog-post-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif; ?>
