<div class="data-first-block" style="color:lightsalmon; border:5px solid lightslategray; padding:30px; display:flex; justify-content: center; align-items: center; flex-direction:column;">
    <h1 style="text-align: center; font-weight: bold; font-size: 50px;"><?php echo $block->getText(); ?></h1>
    <a class="data-link" href="<?php echo $block->getUrlLink(); ?>" style="text-decoration: none; font-size: 30px; font-weight: bold; color:darkred" title="Checkout/Cart/Index">CHECKOUT</a>
</div>
