<?php
    $posts = $block->getPosts()->getItems();
?>

<?php if (count($posts)): ?>
    <div class="blog-post-list" style="display:flex;flex-flow:row wrap;">
        <?php /** @var $post \Semysiuk\BlogModule\Model\Post */ ?>
        <?php foreach ($posts as $post) : ?>
            <div class="blog-post-list-item" style="border:2px solid grey;margin:10px 10px 10px 10px;position:relative;">
                <div class="post-title">
                    <h3 class="blog-post-item-title">
                        <a href="<?php echo $block->getPostUrl($post); ?>"><?php echo $post->getTitle(); ?></a>
                    </h3>
                    <img src="<?php echo $block->getImageUrl($post); ?>"
                         height="<?php echo $block->getImageHeight(); ?>"
                         width="<?php echo $block->getImageWidth(); ?>"/>
                </div>
                <div class="blog-post-item-content">
                    <div class="blog-post-item-discription">
                        <?php echo $post->getDescription(); ?>
                    </div>
                    <div>
                        <p>
                            <?php echo $post->getContent(); ?>
                        </p>
                    </div>
                </div>
                <div class="blog-post-item-meta">
                    <div>
                        <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreatedAt(); ?>
                    </div>
                    <div>
                        <strong><?php echo __('Update at:') ?></strong> <?php echo $post->getUpdateAt(); ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="blog-post-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif; ?>
<?php else : ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('Blog haven\'t posts.'); ?></span></div>
<?php endif; ?>
