<?php
/** @var $block \Semysiuk\BlogModule\Block\Post\View */
/** @var $post \Semysiuk\BlogModule\Api\Data\PostInterface */
/** @var $comments \Semysiuk\BlogModule\Api\Data\CommentInterface */
$post = $block->getPost();
$comments = $block->getComments();
?>

<div class="post-header">
    <h1 class="blog-post-item-title"><?php echo $post->getTitle(); ?></h1>

    <img src="<?php echo $block->getImageUrl($post); ?>"
         height="<?php echo $block->getImageHeight(); ?>"
         width="<?php echo $block->getImageWidth(); ?>"/>
</div>

<div class="blog-post-item-content">
    <div style="min-height: 100px;">
        <?php echo $post->getContent(); ?>
    </div>
</div>
<div class="blog-post-item-meta" style="margin-top:20px;">
    <div>
        <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreatedAt(); ?>
    </div>
    <div>
        <strong><?php echo __('Update at:') ?></strong> <?php echo $post->getUpdateAt(); ?>
    </div>
</div>

<?php if ($block->getPagerHtml()) : ?>
    <div class="blog-post-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif; ?>
