<div class="blog_comment_rules" style="padding: 15px 0;">
    <p style="text-align: center;"><strong>Blog Comment Policy</strong></p>
    <ul>
        <li>Comments deemed to be spam or solely promotional in nature will be deleted. Including a link to relevant content is permitted, but comments should be relevant to the post topic.</li>
        <li>Comments including profanity will be deleted.</li>
        <li>Comments containing language or concepts that could be deemed offensive will be deleted. Note this may include abusive, threatening, pornographic, offensive, misleading or libelous language.</li>
        <li>Comments that harass other posters will be deleted. Please be respectful toward other contributors.</li>
        <li>Anonymous comments will be deleted. We only accept comment from posters who identify themselves.</li>
    </ul>
</div>
