<?php
/**
 * Lebed blog comment view info template
 *
 * @category  Lebed
 * @package   Lebed\Blog
 * @author    Tetiana Lebed <teleb@smile.fr>
 * @copyright 2019 Smile
 */
/** @var \Magento\Backend\Block\Template $block */
/** @var \Lebed\Blog\ViewModel\Comment\Item\InfoViewModel $commentViewModel */
$commentViewModel = $block->getCustomerInfoViewModel();
/** @var Lebed\Blog\Model\Comment $comment */
$comment = $commentViewModel->getComment();
$postId = $comment->getPostId();
$post = $commentViewModel->getPostById($postId);
?>
<div class="row">
    <div class="fieldset-wrapper comment-information col-l-6 col-l-offset-3">
        <div class="fieldset-wrapper-title">
            <span class="title"><?= $block->escapeHtml(__('Comment Information')) ?></span>
        </div>
        <table class="admin__table-secondary">
            <tbody>
                <tr>
                    <th><?= $block->escapeHtml(__('Comment ID:')) ?></th>
                    <td><?= $block->escapeHtml($comment->getId()) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Post (id %1):', $postId)) ?></th>
                    <td><a href="<?= $block->escapeUrl(
                        $block->getUrl('lebed_blog/post/edit', ['id' => $postId])
                        ) ?>" target="_blank"><?= $block->escapeHtml($post->getTitle()) ?></a></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('First name:')) ?></th>
                    <td><?= $block->escapeHtml($comment->getFirstName()) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Last Name:')) ?></th>
                    <td><?= $block->escapeHtml($comment->getLastName()) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('E-mail:')) ?></th>
                    <td><?= $block->escapeHtml($comment->getEmail()) ?></td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Comment Date:')) ?></th>
                    <td><?= $block->escapeHtml($comment->getCreatedAt()) ?></td>
                </tr>
                <tr>
                    <th colspan="2"><?= $block->escapeHtml(__('Comment Text:')) ?></th>
                </tr>
                <tr>
                    <td colspan="2"><?= $block->escapeHtml($comment->getComment()) ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
