<?php
/**
 * Lebed blog comment form template
 *
 * @category  Lebed
 * @package   Lebed\Blog
 * @author    Tetiana Lebed <teleb@smile.fr>
 * @copyright 2019 Smile
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Lebed\Blog\ViewModel\Comment\FormUrlViewModel $formUrlViewModel */
$formUrlViewModel = $block->getFormUrlViewModle();
$actionUrl = $formUrlViewModel->getActionUrl();
?>
<div class="comment-form-wrap">
    <form method="post" class="form" data-mage-init='{"validation":{}}'
          action="<?= $block->escapeUrl($actionUrl) ?>">
        <?= $block->getBlockHtml('formkey') ?>
        <fieldset class="fieldset">
            <legend class="legend"><span><?= $block->escapeHtml(__("Comment Post:")) ?></span></legend>
            <div class="field required">
                <label for="first_name_field" class="label">
                    <span><?= $block->escapeHtml(__('First Name')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="first_name" id="first_name_field" class="input-text"
                           data-validate="{ required: true, maxlength: 255 }" />
                </div>
            </div>
            <div class="field required">
                <label for="last_name_field" class="label">
                    <span><?= $block->escapeHtml(__('Last Name')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="last_name" id="last_name_field" class="input-text"
                           data-validate="{ required: true, maxlength: 255 }" />
                </div>
            </div>
            <div class="field required">
                <label for="email_field" class="label">
                    <span><?= $block->escapeHtml(__('E-mail')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="email" id="email_field" class="input-text"
                           data-validate="{ required: true, email: true }" />
                </div>
            </div>
            <div class="field required">
                <label for="comment_field" class="label"><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
                <div class="control">
                    <textarea name="comment" id="comment_field" data-validate="{required:true}"></textarea>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary actions-primary">
                <button type="submit" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit Comment')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
