<?php
/**
 * Lebed FirstModule renderer wording.phtml
 *
 * @category  Lebed
 * @package   Lebed/FirstModule
 * @author    Tetiana Lebed <teleb@smile.fr>
 * @copyright 2019 Smile
 */
/** @var \Lebed\FirstModule\Block\Renderer\Wording */
/** @var \Lebed\FourthModule\Helper\Data $configData */
$configData = $this->helper('Lebed\FourthModule\Helper\Data');
?>
<h1><?= $block->getText() ?></h1>
<h2><?= $configData->getInputValue(); ?></h2>
