<?php
/**
 * Lebed blog post view template
 *
 * @category  Lebed
 * @package   Lebed\Blog
 * @author    Tetiana Lebed <teleb@smile.fr>
 * @copyright 2019 Smile
 */
/** @var $block \Lebed\Blog\Block\Post\View */
/** @var $post \Lebed\Blog\Api\Data\PostInterface */
$post = $block->getPost();
?>
<div class="post-header">
    <h1 class="blog-post-item-title"><?php echo $post->getTitle(); ?></h1>

    <img src="<?php echo $block->getImageUrl($post); ?>"
         height="<?php echo $block->getImageHeight(); ?>"
         width="<?php echo $block->getImageWidth(); ?>"/>
</div>

<div class="blog-post-item-content">
    <?php echo $post->getContent(); ?>
</div>

<div class="blog-post-item-meta">
    <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreatedAt(); ?>
    <strong><?php echo __('Update at:') ?></strong> <?php echo $post->getUpdateAt(); ?>
</div>
