<?php
/** @var $block \Semysiuk\BlogModule\Block\Comment\Listing */
/** @var $comments \Semysiuk\BlogModule\Api\Data\CommentInterface */
$comments = $block->getCommentsByPost();

?>

<hr/>

<div class="comments">
    <?php if (!count($comments)): ?>
        <h1>NO COMMENTS YET...</h1>
    <?php else : ?>
        <div class="blog-post-comments-list">
            <?php /** @var $comment \Semysiuk\BlogModule\Model\Comment */ ?>
            <?php foreach ($comments as $comment) : ?>
                <div class="blog-post-comment-list-item">
                    <div>
                        <div class="post-comment-title">
                            <h3 class="blog-post-comment-item-title">
                                <?php echo $comment->getComment(); ?>
                            </h3>
                            <?php echo $comment->getDate(); ?>
                        </div>
                        <div>
                            <?php echo $comment->getAnswer(); ?>
                        </div>
                    </div>
                    <?php if ($comment->getAnswer() !== null) : ?>
                    <div style="display:block;margin-left:30px;">
                        <h2>
                            <?php $comment->getAnswer(); ?>
                        </h2>
                    </div>
                    <div>
                        <h2>
                            <?php $comment->getStatus(); ?>
                        </h2>
                    </div>
                    <?php endif; ?>
                </div>
            <hr/>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
