<?php
/**
* Koshyk blog comment listing template
*
* @category  Koshyk
* @package   Koshyk\Blog
* @author    Roman Koshyk <romadaaaa@gmail.com>
*/
/** @var \Koshyk\Blog\Block\Comment\Listing $block */
?>
<?php $comments = $block->getComments()->getItems(); ?>
<?php if (count($comments)): ?>
<div class="blog-post-list">
    <?php /** @var $comment \Koshyk\Blog\Model\Comment */ ?>
    <?php foreach ($comments as $comment) : ?>
        <div class="blog-comment-list-item">
            <div class="comment-title">
                <h3 class="blog-comment-item-name">
                    <?php echo $comment->getFirstName(); ?>
                    <?php echo $comment->getLastName(); ?>
                </h3>
                <h3 class="blog-comment-item-email">
                    <?php echo $comment->getEmail(); ?>
                </h3>
            </div>
            <div class="blog-comment-item-content">
                <div class="blog-comment-item-comment">
                    <?php echo $comment->getComment(); ?>
                </div>
                <div class="blog-comment-item-answer">
                    <?php echo $comment->getAnswer(); ?>
                </div>

                <div class="blog-comment-item-meta">
                    <strong><?php echo __('Created at:') ?></strong> <?php echo $comment->getCreateDate() ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="blog-comment-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif; ?>
</div>
<?php else : ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('Blog haven\'t comments.'); ?></span></div>
<?php endif; ?>
