<?php
/** @var $block \Dehtiarov\BlogVideh\Block\Comment\Comments */
/** @var $post \Dehtiarov\BlogVideh\Api\Data\CommentInterface */

$customerInfo = $block->getCustomerInfo();
?>

<h1>Add comment</h1>
<form class="form addcommnet"
      action="<?= $block->getCommentActionUrl(); ?>"
      id="comment-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field first_name required">
            <label class="label" for="first_name"><span><?= $block->escapeHtml(__('First name')) ?></span></label>
            <div class="control">
                <input name="first_name" id="first_name" title="<?= $block->escapeHtmlAttr(__('First name')) ?>" value="<?= $customerInfo['first_name'] ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field last_name required">
            <label class="label" for="last_name"><span><?= $block->escapeHtml(__('Last name')) ?></span></label>
            <div class="control">
                <input name="last_name" id="last_name" title="<?= $block->escapeHtmlAttr(__('Last name')) ?>" value="<?= $customerInfo['last_name'] ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $customerInfo['email'] ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('Your Comment')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Your Comment')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="post_id" id="post_id" value="<?= $this->getPostId(); ?>" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>